modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="cobblemontavern"
version="${mod_version}"
displayName="${mod_name}"
description='''
Cobblemon Tavern Mod
'''

[[dependencies.cobblemontavern]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemontavern]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemontavern]]
modId="kaleidoscope_tavern"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.cobblemontavern]]
modId="cobblemon"
type="required"
versionRange="[1.7.3,)"
ordering="NONE"
side="BOTH"